### ISSUE TITLE
Hello, testnet!

### ISSUE THREAD

**Issue by atversko** [msteckyefantis/libra-node#1]
Hello!

Will you do nodejs libra script for testnet? Or you are waiting for live version?

**Comment by msteckyefantis** [comment]
Hello @gumacuk15 ,

Sorry for the delayed reply, did not catch the notification for this message.

To answer your question, I do think it would make sense for this library to work with both the test and the live nets. It should be easy to switch between the two, with a single env configuration or something along the lines of that.

Thanks for your question and interest in this library, please don't hesitate to ask if you have any more questions.
